[package]
name = "cumulus-primitives-utility"
version = "0.7.3"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Helper datatypes for Cumulus"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.20", default-features = false }

# Substrate
frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "28.0.0" }
sp-io = { path = "../../../substrate/primitives/io", default-features = false, version = "30.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "14.0.0" }

# Polkadot
polkadot-runtime-common = { path = "../../../polkadot/runtime/common", default-features = false, version = "7.0.0" }
polkadot-runtime-parachains = { path = "../../../polkadot/runtime/parachains", default-features = false, version = "7.0.0" }
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", default-features = false, version = "7.0.0" }
xcm-executor = { package = "staging-xcm-executor", path = "../../../polkadot/xcm/xcm-executor", default-features = false, version = "7.0.3" }
xcm-builder = { package = "staging-xcm-builder", path = "../../../polkadot/xcm/xcm-builder", default-features = false, version = "7.0.3" }

# Cumulus
cumulus-primitives-core = { path = "../core", default-features = false, version = "0.7.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"log/std",
	"polkadot-runtime-common/std",
	"polkadot-runtime-parachains/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]

runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
